{
  "info": {
    "author": "Philipe",
    "author_email": "philipe.rp@gmail.com",
    "bugtrack_url": null,
    "classifiers": [],
    "description": "=======\nhttp403\n=======\n\nHttp403 response from http://devwithpassion.com/felipe/manipulando-erros-http-403-permissao-negada-no-django/\n\nThis will be integrated with django-response-helpers\n\nhttps://github.com/chronossc/django-response-helpers/\nhttps://github.com/imtapps/django-response-helpers\nhttp://pypi.python.org/pypi/django-response-helpers",
    "docs_url": null,
    "download_url": "UNKNOWN",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/chronossc/http403",
    "keywords": "django,exceptions,http403",
    "license": "LICENSE",
    "maintainer": null,
    "maintainer_email": null,
    "name": "django-extra-exceptions",
    "platform": "any",
    "project_url": "https://pypi.org/project/django-extra-exceptions/",
    "release_url": "https://pypi.org/project/django-extra-exceptions/1.0.1/",
    "requires_python": null,
    "summary": "Extra exception handling to mirror django.http.http404",
    "version": "1.0.1"
  },
  "releases": {
    "1.0.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "054eccd562631e21687586ce9db011e1",
          "sha256": "c697b22abb49b66bcb3be48327e95a107d5f1230fd1e412e44cd22278b1f2f39"
        },
        "downloads": 2976,
        "filename": "django-extra-exceptions-1.0.0.tar.gz",
        "has_sig": false,
        "md5_digest": "054eccd562631e21687586ce9db011e1",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2392,
        "upload_time": "2012-07-27T19:50:44",
        "url": "https://files.pythonhosted.org/packages/00/35/a08cf74b7f2a6cfced49ee52a724ae2cf79bb63fd793f122e725fa26f416/django-extra-exceptions-1.0.0.tar.gz"
      }
    ],
    "1.0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "7706d2b61b6b1b933290e4d38f43c4ff",
          "sha256": "b5d8e20b01985e89c90e3383543a63dee9a6d2336a5c075ed4e4e177357111b9"
        },
        "downloads": 3047,
        "filename": "django-extra-exceptions-1.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "7706d2b61b6b1b933290e4d38f43c4ff",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2596,
        "upload_time": "2012-07-27T20:30:12",
        "url": "https://files.pythonhosted.org/packages/a4/ca/32edbe12341236109df8019e831af470dedc7894bd1b44eb08bd848d30e4/django-extra-exceptions-1.0.1.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "7706d2b61b6b1b933290e4d38f43c4ff",
        "sha256": "b5d8e20b01985e89c90e3383543a63dee9a6d2336a5c075ed4e4e177357111b9"
      },
      "downloads": 3047,
      "filename": "django-extra-exceptions-1.0.1.tar.gz",
      "has_sig": false,
      "md5_digest": "7706d2b61b6b1b933290e4d38f43c4ff",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 2596,
      "upload_time": "2012-07-27T20:30:12",
      "url": "https://files.pythonhosted.org/packages/a4/ca/32edbe12341236109df8019e831af470dedc7894bd1b44eb08bd848d30e4/django-extra-exceptions-1.0.1.tar.gz"
    }
  ]
}