{
  "info": {
    "author": "Tae-lim Oh",
    "author_email": "taelimoh@gmail.com",
    "bugtrack_url": null,
    "classifiers": [],
    "description": "",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://gitlab.com/taelimoh/drf_logged_validation_error",
    "keywords": "django rest framework log validation error",
    "license": "MIT",
    "maintainer": "",
    "maintainer_email": "",
    "name": "drf-logged-validation-error",
    "platform": "",
    "project_url": "https://pypi.org/project/drf-logged-validation-error/",
    "release_url": "https://pypi.org/project/drf-logged-validation-error/0.2/",
    "requires_dist": [],
    "requires_python": "",
    "summary": "Raise validation with log in Django REST Framework API",
    "version": "0.2"
  },
  "releases": {
    "0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "33e2741b6ebffe90dbdfd22dcc3345bd",
          "sha256": "b181c2f24d2802eda85e1b021c77bff43b133ed06d02034554a3649b183bbb7a"
        },
        "downloads": -1,
        "filename": "drf_logged_validation_error-0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "33e2741b6ebffe90dbdfd22dcc3345bd",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 1392,
        "upload_time": "2017-02-04T02:04:24",
        "url": "https://files.pythonhosted.org/packages/0d/de/ae69b4ccd7183fdfac948ede33bab254ac90220f87dda17547162c95aeee/drf_logged_validation_error-0.1.tar.gz"
      }
    ],
    "0.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "c44c64b04b1621f672b9a1a49ec37ce9",
          "sha256": "b83ffe8d96dd417a7d64bb816250251c967a5ae495befd5a5a289371495802d6"
        },
        "downloads": -1,
        "filename": "drf_logged_validation_error-0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "c44c64b04b1621f672b9a1a49ec37ce9",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 1403,
        "upload_time": "2017-11-17T06:45:45",
        "url": "https://files.pythonhosted.org/packages/7e/1b/3c34540224d87e0265a1f754b65c1e0c33d85bb19b9678931301bb375402/drf_logged_validation_error-0.2.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "c44c64b04b1621f672b9a1a49ec37ce9",
        "sha256": "b83ffe8d96dd417a7d64bb816250251c967a5ae495befd5a5a289371495802d6"
      },
      "downloads": -1,
      "filename": "drf_logged_validation_error-0.2.tar.gz",
      "has_sig": false,
      "md5_digest": "c44c64b04b1621f672b9a1a49ec37ce9",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 1403,
      "upload_time": "2017-11-17T06:45:45",
      "url": "https://files.pythonhosted.org/packages/7e/1b/3c34540224d87e0265a1f754b65c1e0c33d85bb19b9678931301bb375402/drf_logged_validation_error-0.2.tar.gz"
    }
  ]
}