{
  "info": {
    "author": "Jonas Haag",
    "author_email": "jonas@lophus.org",
    "bugtrack_url": null,
    "classifiers": [
      "Intended Audience :: Developers",
      "License :: OSI Approved :: ISC License (ISCL)",
      "Programming Language :: Python",
      "Programming Language :: Python :: 3.4",
      "Programming Language :: Python :: 3.5",
      "Programming Language :: Python :: 3.6"
    ],
    "description": "",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/cashlink/error-boundary",
    "keywords": "",
    "license": "",
    "maintainer": "",
    "maintainer_email": "",
    "name": "error_boundary",
    "platform": "",
    "project_url": "https://pypi.org/project/error_boundary/",
    "release_url": "https://pypi.org/project/error_boundary/1.0.0/",
    "requires_dist": [],
    "requires_python": "",
    "summary": "Error boundaries for Python",
    "version": "1.0.0"
  },
  "releases": {
    "1.0.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "b94165d03293c22460b5f82a7273a36a",
          "sha256": "63e66975b230d687f21cc4948c01883f50e38bd1c7a30a20b58bda164b42cdfa"
        },
        "downloads": -1,
        "filename": "error_boundary-1.0.0.tar.gz",
        "has_sig": false,
        "md5_digest": "b94165d03293c22460b5f82a7273a36a",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 4376,
        "upload_time": "2017-12-01T22:23:42",
        "url": "https://files.pythonhosted.org/packages/d2/6d/cf87e9cf951f68ddd3f09b41f667b3606725fdc09544a4eeba0dfd7caf12/error_boundary-1.0.0.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "b94165d03293c22460b5f82a7273a36a",
        "sha256": "63e66975b230d687f21cc4948c01883f50e38bd1c7a30a20b58bda164b42cdfa"
      },
      "downloads": -1,
      "filename": "error_boundary-1.0.0.tar.gz",
      "has_sig": false,
      "md5_digest": "b94165d03293c22460b5f82a7273a36a",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 4376,
      "upload_time": "2017-12-01T22:23:42",
      "url": "https://files.pythonhosted.org/packages/d2/6d/cf87e9cf951f68ddd3f09b41f667b3606725fdc09544a4eeba0dfd7caf12/error_boundary-1.0.0.tar.gz"
    }
  ]
}