{
  "info": {
    "author": "Google Cloud Platform",
    "author_email": "jjg+google-cloud-python@google.com",
    "bugtrack_url": "",
    "classifiers": [
      "Development Status :: 3 - Alpha",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: Apache Software License",
      "Operating System :: OS Independent",
      "Programming Language :: Python :: 2",
      "Programming Language :: Python :: 2.7",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3.4",
      "Programming Language :: Python :: 3.5",
      "Programming Language :: Python :: 3.6",
      "Topic :: Internet"
    ],
    "description": "Python Client for Stackdriver Error Reporting\n=============================================\n\n    Python idiomatic client for `Stackdriver Error Reporting`_\n\n.. _Stackdriver Error Reporting: https://cloud.google.com/error-reporting/\n\n|pypi| |versions|\n\n-  `Documentation`_\n\n.. _Documentation: https://googlecloudplatform.github.io/google-cloud-python/stable/error-reporting-usage.html\n\nQuick Start\n-----------\n\n.. code-block:: console\n\n    $ pip install --upgrade google-cloud-error-reporting\n\nAuthentication\n--------------\n\nWith ``google-cloud-python`` we try to make authentication as painless as\npossible. Check out the `Authentication section`_ in our documentation to\nlearn more. You may also find the `authentication document`_ shared by all\nthe ``google-cloud-*`` libraries to be helpful.\n\n.. _Authentication section: http://google-cloud-python.readthedocs.io/en/latest/google-cloud-auth.html\n.. _authentication document: https://github.com/GoogleCloudPlatform/gcloud-common/tree/master/authentication\n\nUsing the API\n-------------\n\nThe Stackdriver `Error Reporting`_ API (`Error Reporting API docs`_)\ncounts, analyzes and aggregates the crashes in your running cloud services.\nA centralized error management interface displays the results with sorting\nand filtering capabilities. A dedicated view shows the error details: time\nchart, occurrences, affected user count, first and last seen dates and a\ncleaned exception stack trace. Opt-in to receive email and mobile alerts\non new errors.\n\n.. _Error Reporting: https://cloud.google.com/error-reporting/\n.. _Error Reporting API docs: https://cloud.google.com/error-reporting/reference/\n\nSee the ``google-cloud-python`` API Error Reporting `Documentation`_ to learn\nhow to get started using this library.\n\n.. |pypi| image:: https://img.shields.io/pypi/v/google-cloud-error-reporting.svg\n   :target: https://pypi.python.org/pypi/google-cloud-error-reporting\n.. |versions| image:: https://img.shields.io/pypi/pyversions/google-cloud-error-reporting.svg\n   :target: https://pypi.python.org/pypi/google-cloud-error-reporting\n\n\n",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/GoogleCloudPlatform/google-cloud-python",
    "keywords": "",
    "license": "Apache 2.0",
    "maintainer": "",
    "maintainer_email": "",
    "name": "google-cloud-error-reporting",
    "platform": "Posix; MacOS X; Windows",
    "project_url": "https://pypi.org/project/google-cloud-error-reporting/",
    "release_url": "https://pypi.org/project/google-cloud-error-reporting/0.25.0/",
    "requires_dist": [
      "google-cloud-logging (<2.0dev,>=1.0.0)",
      "google-cloud-core (>=0.25.0,<0.26dev)",
      "gapic-google-cloud-error-reporting-v1beta1 (<0.16dev,>=0.15.0)"
    ],
    "requires_python": "",
    "summary": "Python Client for Stackdriver Error Reporting",
    "version": "0.25.0"
  },
  "releases": {
    "0.0.1": [],
    "0.20.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "2392970b2a739955c9a2fb16b9d9df22",
          "sha256": "cf645274df7d3876aabc1fbc0df353e2382dfdc920f1597961d3ae1c9113c37b"
        },
        "downloads": 2313,
        "filename": "google_cloud_error_reporting-0.20.0-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "2392970b2a739955c9a2fb16b9d9df22",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 10559,
        "upload_time": "2016-09-29T00:23:06",
        "url": "https://files.pythonhosted.org/packages/34/3f/8833b940e1e2165283508282f0189f3449d1545583967ecb8035bcd9de91/google_cloud_error_reporting-0.20.0-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "4b6fc4fdea5799f7ae4fee6afc006eac",
          "sha256": "ad0f7fa4718c40e3655c594bccadf21bbc230f4f0b22229140d41b51c418fc50"
        },
        "downloads": 166,
        "filename": "google-cloud-error-reporting-0.20.0.tar.gz",
        "has_sig": false,
        "md5_digest": "4b6fc4fdea5799f7ae4fee6afc006eac",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 6541,
        "upload_time": "2016-09-29T00:23:08",
        "url": "https://files.pythonhosted.org/packages/46/93/a3b1796ff154a771baea2e80074ef1c5d5b2a35a453b601b394b42b49fbd/google-cloud-error-reporting-0.20.0.tar.gz"
      }
    ],
    "0.21.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "4ac474f07eff8d6408939df4b25108e1",
          "sha256": "af81b5f146aab6303e8ae5ebb6ebdc88a8aa35012adc43d834dc8a04dadb8d3e"
        },
        "downloads": 2866,
        "filename": "google_cloud_error_reporting-0.21.0-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "4ac474f07eff8d6408939df4b25108e1",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 10770,
        "upload_time": "2016-11-14T22:52:52",
        "url": "https://files.pythonhosted.org/packages/b4/8c/3dd873ec38f13451fe771a4e9a8c8570a0a768f5050f71adaa39544fa913/google_cloud_error_reporting-0.21.0-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "15c754c5cf9b5d335cf8a0577713968f",
          "sha256": "b6741b0f9e59c5e53c2deba4034d0a3ab1b66607d444bbf436a941d09dd40904"
        },
        "downloads": 101,
        "filename": "google-cloud-error-reporting-0.21.0.tar.gz",
        "has_sig": false,
        "md5_digest": "15c754c5cf9b5d335cf8a0577713968f",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 6627,
        "upload_time": "2016-11-14T22:52:54",
        "url": "https://files.pythonhosted.org/packages/bf/76/e02243ecefd9d8da190a40f79d8c76172363c1347e809e4f9ea28dadc7d1/google-cloud-error-reporting-0.21.0.tar.gz"
      }
    ],
    "0.22.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "3a648c3d2782ecb6f058ac712d8a9ba3",
          "sha256": "356f4277b61b5c7fd169c4d26af9a4f8afd325a8c336845e36255f8518c94e4a"
        },
        "downloads": 5289,
        "filename": "google_cloud_error_reporting-0.22.0-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "3a648c3d2782ecb6f058ac712d8a9ba3",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 12730,
        "upload_time": "2016-12-10T20:53:47",
        "url": "https://files.pythonhosted.org/packages/90/a3/291f2fbe545ed5c217b44a2d2bf4d5c4c9b36f97393b2cdc4c975e10404e/google_cloud_error_reporting-0.22.0-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "5f187c5d288200c5a16af095ac816360",
          "sha256": "8c92445ee76e3273b5d3a98e0c51b19b928784242b84e89149b2867fb415ca7a"
        },
        "downloads": 97,
        "filename": "google-cloud-error-reporting-0.22.0.tar.gz",
        "has_sig": false,
        "md5_digest": "5f187c5d288200c5a16af095ac816360",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 7281,
        "upload_time": "2016-12-10T20:53:48",
        "url": "https://files.pythonhosted.org/packages/aa/94/268668367061a901a73ca2a263f3c8d136cd53913c343d8a329ee76fbe7b/google-cloud-error-reporting-0.22.0.tar.gz"
      }
    ],
    "0.23.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "4d1e4747e0243da456ed2aaed681e729",
          "sha256": "9461ecbdcb333c7803f6fe5f7234c1871ac15cd20afc6f08e8ab7a8b58f79cec"
        },
        "downloads": 23,
        "filename": "google_cloud_error_reporting-0.23.0-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "4d1e4747e0243da456ed2aaed681e729",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 18434,
        "upload_time": "2017-02-25T00:27:10",
        "url": "https://files.pythonhosted.org/packages/a5/3a/d160bb9b9bac23f6f2efd63ce9776e79e12db5a8aac5da07ec8465cf4e23/google_cloud_error_reporting-0.23.0-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "3cde474f852b5f4daa6a62b06ad9a793",
          "sha256": "924061585a05d3f7e1df440c43e802bdaeb8735f54b7a12e6fb4196cbaae2aa4"
        },
        "downloads": 12,
        "filename": "google-cloud-error-reporting-0.23.0.tar.gz",
        "has_sig": false,
        "md5_digest": "3cde474f852b5f4daa6a62b06ad9a793",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 9871,
        "upload_time": "2017-02-25T00:27:11",
        "url": "https://files.pythonhosted.org/packages/dc/59/89d65b99acb3336f899cd38617c4075307931ecbf7173ccebbe4133df991/google-cloud-error-reporting-0.23.0.tar.gz"
      }
    ],
    "0.23.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "e50b6ab7d937f98119578cb3729f23da",
          "sha256": "c536bf728810846e272e85978d0757d9c3f5b1419a2141a4ba19890b91aeab6e"
        },
        "downloads": 525,
        "filename": "google_cloud_error_reporting-0.23.1-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "e50b6ab7d937f98119578cb3729f23da",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 18719,
        "upload_time": "2017-03-08T17:51:07",
        "url": "https://files.pythonhosted.org/packages/50/24/71cfbee9d3f6b1e29bf169ed858c92d624b77f7c9b8821688604f5153669/google_cloud_error_reporting-0.23.1-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "52b08b8c6f42f3bc127fa54863617b60",
          "sha256": "54b41de4e9e539986923edb14216d393d9922ade4bc324a814d9bc0856429deb"
        },
        "downloads": 37,
        "filename": "google-cloud-error-reporting-0.23.1.tar.gz",
        "has_sig": false,
        "md5_digest": "52b08b8c6f42f3bc127fa54863617b60",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 10240,
        "upload_time": "2017-03-08T17:51:08",
        "url": "https://files.pythonhosted.org/packages/e0/86/cc8ba08e263bd6f2e70bc6d92aec1bebee0edc9b3e7a2a0fb2e580a82829/google-cloud-error-reporting-0.23.1.tar.gz"
      }
    ],
    "0.23.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "5d59d5aab64e5be858e9b6c0a5c046f1",
          "sha256": "04975d20e9d8029a43b22f1092e8ecaf46336bbb6aa8ee0f2467b9e6f4a21094"
        },
        "downloads": 466,
        "filename": "google_cloud_error_reporting-0.23.2-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "5d59d5aab64e5be858e9b6c0a5c046f1",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 18864,
        "upload_time": "2017-03-28T18:56:20",
        "url": "https://files.pythonhosted.org/packages/a2/d3/dd41e23e524402e8f0db1b0aadd0ff8452f59af24dda2110e6bd2310ae10/google_cloud_error_reporting-0.23.2-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "f58d1d606bef8d2e2f0a2bcae046ae28",
          "sha256": "f1bd7eed355e13aaec14c1afff87f572cdcec317565d04e60c6e5f19c4df7d4c"
        },
        "downloads": 12,
        "filename": "google-cloud-error-reporting-0.23.2.tar.gz",
        "has_sig": false,
        "md5_digest": "f58d1d606bef8d2e2f0a2bcae046ae28",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 14542,
        "upload_time": "2017-03-28T18:56:22",
        "url": "https://files.pythonhosted.org/packages/d5/d3/8b7b0fde1fe4aaa8956d29f73cf42486e5766bc710b6cdeae9dbe2850ce9/google-cloud-error-reporting-0.23.2.tar.gz"
      }
    ],
    "0.24.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "6d740ed4956becdca44f4ad4ca30f95b",
          "sha256": "d728615c7c63622ab0d1fd7cd286c6c40c8f9d7cfe7118694eb605937fd52107"
        },
        "downloads": 1591,
        "filename": "google_cloud_error_reporting-0.24.0-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "6d740ed4956becdca44f4ad4ca30f95b",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 18913,
        "upload_time": "2017-04-01T02:09:33",
        "url": "https://files.pythonhosted.org/packages/97/f3/62a363e83f9fc5c27ce2d6e51a851b7f111dd01a347cd2113c6cac65eec4/google_cloud_error_reporting-0.24.0-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "68a31c4c862623c77ba27b6e4ad9d224",
          "sha256": "73226a831bb2369b7261e7b2ded82d7d6f58aaab9d5bd6fc68738e1bef93e3a1"
        },
        "downloads": 35,
        "filename": "google-cloud-error-reporting-0.24.0.tar.gz",
        "has_sig": false,
        "md5_digest": "68a31c4c862623c77ba27b6e4ad9d224",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 13482,
        "upload_time": "2017-04-01T02:09:34",
        "url": "https://files.pythonhosted.org/packages/1a/a6/2af763d329d3ec16c866d78dd09b67f0e5192fea35a5bd9fe35707533465/google-cloud-error-reporting-0.24.0.tar.gz"
      }
    ],
    "0.24.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "7ee830d541ae931124a83ab0e8d0798b",
          "sha256": "1c9bd0c9a8c75d2eb6f03bdaf7e809f48193addfd3d35bd7a16291e246f79984"
        },
        "downloads": 0,
        "filename": "google_cloud_error_reporting-0.24.1-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "7ee830d541ae931124a83ab0e8d0798b",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 18947,
        "upload_time": "2017-04-19T20:59:00",
        "url": "https://files.pythonhosted.org/packages/4a/2f/184663e23a014ed6ad09757808f8ce60353d381e5e48347f58d06402f076/google_cloud_error_reporting-0.24.1-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "9aabbbed92094dc41441d39d10016beb",
          "sha256": "e40b37029ac428b0ae8f30744e13ccfd4569446cb9f3079ae6ca3367739e8cf5"
        },
        "downloads": 0,
        "filename": "google-cloud-error-reporting-0.24.1.tar.gz",
        "has_sig": false,
        "md5_digest": "9aabbbed92094dc41441d39d10016beb",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 13496,
        "upload_time": "2017-04-19T20:59:02",
        "url": "https://files.pythonhosted.org/packages/0d/1d/2f1b0f8be5b3f10dcec864e50889ae26fe21f80d01c43eb3bd17b77de33b/google-cloud-error-reporting-0.24.1.tar.gz"
      }
    ],
    "0.24.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "a1adf903eec5ada6bff3c16ff2171dee",
          "sha256": "327340428fc2ee6f7e4174da95e4fa62f23462e3c9854cc2a7c6d7f06d7fef79"
        },
        "downloads": 0,
        "filename": "google_cloud_error_reporting-0.24.2-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "a1adf903eec5ada6bff3c16ff2171dee",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 13304,
        "upload_time": "2017-04-28T18:24:52",
        "url": "https://files.pythonhosted.org/packages/15/32/c7a699c6858368ee416d2eac2785fb73ea62c820b34b20bf5918c37f38e5/google_cloud_error_reporting-0.24.2-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "be3e4c53b8c28f6ffd240f3768124bdc",
          "sha256": "0b38568c3e9538c7f814d73c2e545a4ba1dcb7c928075c64fec9f5f33307430a"
        },
        "downloads": 0,
        "filename": "google-cloud-error-reporting-0.24.2.tar.gz",
        "has_sig": false,
        "md5_digest": "be3e4c53b8c28f6ffd240f3768124bdc",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 11393,
        "upload_time": "2017-04-28T18:24:53",
        "url": "https://files.pythonhosted.org/packages/47/c6/299314c16221b74bcd0ae3de5d2a4898e1886a583586bcf133ba1d3e5758/google-cloud-error-reporting-0.24.2.tar.gz"
      }
    ],
    "0.25.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "eb1f9e3ec34ea9e989db90fb43c7b1de",
          "sha256": "445ced2628f59d13db23f0e2277a9cd0a7b14cf9296f9bd4a439b63f5cff0159"
        },
        "downloads": 0,
        "filename": "google_cloud_error_reporting-0.25.0-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "eb1f9e3ec34ea9e989db90fb43c7b1de",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 13358,
        "upload_time": "2017-06-26T23:48:27",
        "url": "https://files.pythonhosted.org/packages/ba/1d/0c75d8d25895932662e087c3d1103317843d0b1091a7a578a299ae707cc7/google_cloud_error_reporting-0.25.0-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "e40eca9080e9a556d799d4aa55078750",
          "sha256": "7a10b091190478e91bd3ae10e99a32559c1590066ead4ab55c9f4b8fee9f7d9b"
        },
        "downloads": 0,
        "filename": "google-cloud-error-reporting-0.25.0.tar.gz",
        "has_sig": false,
        "md5_digest": "e40eca9080e9a556d799d4aa55078750",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 12573,
        "upload_time": "2017-06-26T23:48:28",
        "url": "https://files.pythonhosted.org/packages/70/1d/5b6b381f4eee94a44b28428c69d45fcd142b307610acd356ee886dda040d/google-cloud-error-reporting-0.25.0.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "eb1f9e3ec34ea9e989db90fb43c7b1de",
        "sha256": "445ced2628f59d13db23f0e2277a9cd0a7b14cf9296f9bd4a439b63f5cff0159"
      },
      "downloads": 0,
      "filename": "google_cloud_error_reporting-0.25.0-py2.py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "eb1f9e3ec34ea9e989db90fb43c7b1de",
      "packagetype": "bdist_wheel",
      "python_version": "py2.py3",
      "size": 13358,
      "upload_time": "2017-06-26T23:48:27",
      "url": "https://files.pythonhosted.org/packages/ba/1d/0c75d8d25895932662e087c3d1103317843d0b1091a7a578a299ae707cc7/google_cloud_error_reporting-0.25.0-py2.py3-none-any.whl"
    },
    {
      "comment_text": "",
      "digests": {
        "md5": "e40eca9080e9a556d799d4aa55078750",
        "sha256": "7a10b091190478e91bd3ae10e99a32559c1590066ead4ab55c9f4b8fee9f7d9b"
      },
      "downloads": 0,
      "filename": "google-cloud-error-reporting-0.25.0.tar.gz",
      "has_sig": false,
      "md5_digest": "e40eca9080e9a556d799d4aa55078750",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 12573,
      "upload_time": "2017-06-26T23:48:28",
      "url": "https://files.pythonhosted.org/packages/70/1d/5b6b381f4eee94a44b28428c69d45fcd142b307610acd356ee886dda040d/google-cloud-error-reporting-0.25.0.tar.gz"
    }
  ]
}