{
  "info": {
    "author": "Mark Veltzer",
    "author_email": "mark.veltzer@gmail.com",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 3 - Alpha",
      "Intended Audience :: Developers",
      "Programming Language :: Python :: 3"
    ],
    "description": "pyerrors is a way to aggregate and report on a host of errors",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://veltzer.github.io/pyerrors",
    "keywords": "python errors aggregate print enum",
    "license": "MIT",
    "maintainer": "",
    "maintainer_email": "",
    "name": "pyerrors",
    "platform": "",
    "project_url": "https://pypi.org/project/pyerrors/",
    "release_url": "https://pypi.org/project/pyerrors/0.0.8/",
    "requires_python": "",
    "summary": "pyerrors is a way to aggregate and report on a host of errors",
    "version": "0.0.8"
  },
  "releases": {
    "0.0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "6724d93efba8dd3218e4db8021844a54",
          "sha256": "7fd9de8571f90a1fa41d75c481b67caff20b6028de68f0302f8c31b2714410f7"
        },
        "downloads": 82,
        "filename": "pyerrors-0.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "6724d93efba8dd3218e4db8021844a54",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 8263,
        "upload_time": "2016-12-21T12:23:27",
        "url": "https://files.pythonhosted.org/packages/ad/ff/a7bb37403c4e0d58261114ffefb56cd902dc7c77b109885854270e5904eb/pyerrors-0.0.1.tar.gz"
      }
    ],
    "0.0.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "e2adc7455dae413f0e0961cd9a404107",
          "sha256": "ab982230187f6e3ba7543963c81a39cd88a1d788d358819afd8dca659693576f"
        },
        "downloads": 204,
        "filename": "pyerrors-0.0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "e2adc7455dae413f0e0961cd9a404107",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 8300,
        "upload_time": "2016-12-22T14:28:39",
        "url": "https://files.pythonhosted.org/packages/6e/4f/3899358b7ab15d64639988bfc74fe73fe4b7298478fe3736bd74ab3ddd63/pyerrors-0.0.2.tar.gz"
      }
    ],
    "0.0.3": [
      {
        "comment_text": "",
        "digests": {
          "md5": "bfc5470350735e3e7715a8937ba3c3ff",
          "sha256": "11a555371658c31d96a2e03fc4d8e68c000fb13a41cef8a689f93e30f6fee703"
        },
        "downloads": 203,
        "filename": "pyerrors-0.0.3.tar.gz",
        "has_sig": false,
        "md5_digest": "bfc5470350735e3e7715a8937ba3c3ff",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 8326,
        "upload_time": "2016-12-22T14:32:00",
        "url": "https://files.pythonhosted.org/packages/0f/73/41de64615b5b3283c2371d22b0620152616367135edecd76c23e994c0bd7/pyerrors-0.0.3.tar.gz"
      }
    ],
    "0.0.4": [
      {
        "comment_text": "",
        "digests": {
          "md5": "1d5ff4e93f55bb706789a02b80d75c8f",
          "sha256": "f4626f8dbe7652647dc9c2462d3573b0d437545685289b4226251889dbdf3ee6"
        },
        "downloads": 206,
        "filename": "pyerrors-0.0.4.tar.gz",
        "has_sig": false,
        "md5_digest": "1d5ff4e93f55bb706789a02b80d75c8f",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 8333,
        "upload_time": "2016-12-22T14:37:41",
        "url": "https://files.pythonhosted.org/packages/2a/cc/0f52ad476d55c96470397d79c07be405a8e055d4ddda4d00fef82a8e5e2f/pyerrors-0.0.4.tar.gz"
      }
    ],
    "0.0.5": [
      {
        "comment_text": "",
        "digests": {
          "md5": "cb48cc7042f1629cb51814ee826be0c2",
          "sha256": "82fb89b796e1da8f79cec3692ff9fa56308c98e0e52b0b63b8f9fe9f0fc6dadd"
        },
        "downloads": 297,
        "filename": "pyerrors-0.0.5.tar.gz",
        "has_sig": false,
        "md5_digest": "cb48cc7042f1629cb51814ee826be0c2",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 9434,
        "upload_time": "2016-12-26T09:48:24",
        "url": "https://files.pythonhosted.org/packages/03/13/a7f8c6dbbea77af4c0cfce6f593be2fad329c326a2d15826906875df0b79/pyerrors-0.0.5.tar.gz"
      }
    ],
    "0.0.6": [
      {
        "comment_text": "",
        "digests": {
          "md5": "87b476025cbd7609e7e023e1fb9da9db",
          "sha256": "1778e2f71d2b3e74a063793c85c6be053c84c7520a25b371f669b74361f0638a"
        },
        "downloads": 294,
        "filename": "pyerrors-0.0.6.tar.gz",
        "has_sig": false,
        "md5_digest": "87b476025cbd7609e7e023e1fb9da9db",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 9656,
        "upload_time": "2016-12-27T09:36:43",
        "url": "https://files.pythonhosted.org/packages/03/d8/ac06f54a1f3ff89c859fb4890bd24f265eed3f253b220729332484f81e12/pyerrors-0.0.6.tar.gz"
      }
    ],
    "0.0.7": [
      {
        "comment_text": "",
        "digests": {
          "md5": "ff33570cd2c9521c8d46cbc74c02597d",
          "sha256": "7902db940460672e71d342434ad4070d4cd6c93bd5d7dfac4e45488d345c052f"
        },
        "downloads": 17,
        "filename": "pyerrors-0.0.7.tar.gz",
        "has_sig": false,
        "md5_digest": "ff33570cd2c9521c8d46cbc74c02597d",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 8112,
        "upload_time": "2017-03-01T12:30:24",
        "url": "https://files.pythonhosted.org/packages/2e/a3/49717d6efa5ce5f7e4b324eec53288b5f15b1773c7ef6470c3dca882b5fd/pyerrors-0.0.7.tar.gz"
      }
    ],
    "0.0.8": [
      {
        "comment_text": "",
        "digests": {
          "md5": "e0bbc195b3589c18a17483c4bd971614",
          "sha256": "e8236d83d397535ed9a5d3301c10d69ff1970770a809babfe0722b1651f7025d"
        },
        "downloads": 0,
        "filename": "pyerrors-0.0.8.tar.gz",
        "has_sig": false,
        "md5_digest": "e0bbc195b3589c18a17483c4bd971614",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 8065,
        "upload_time": "2017-04-20T12:40:28",
        "url": "https://files.pythonhosted.org/packages/ff/3b/34c5f8cf25a0735910a06e1759d16e2f46b1a07cbf698be5dd517355f1b7/pyerrors-0.0.8.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "e0bbc195b3589c18a17483c4bd971614",
        "sha256": "e8236d83d397535ed9a5d3301c10d69ff1970770a809babfe0722b1651f7025d"
      },
      "downloads": 0,
      "filename": "pyerrors-0.0.8.tar.gz",
      "has_sig": false,
      "md5_digest": "e0bbc195b3589c18a17483c4bd971614",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 8065,
      "upload_time": "2017-04-20T12:40:28",
      "url": "https://files.pythonhosted.org/packages/ff/3b/34c5f8cf25a0735910a06e1759d16e2f46b1a07cbf698be5dd517355f1b7/pyerrors-0.0.8.tar.gz"
    }
  ]
}