{
  "info": {
    "author": "Victor Stinner",
    "author_email": "victor.stinner@gmail.com",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 3 - Alpha",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Natural Language :: English",
      "Operating System :: OS Independent",
      "Programming Language :: C",
      "Programming Language :: Python",
      "Topic :: Security",
      "Topic :: Software Development :: Debuggers",
      "Topic :: Software Development :: Libraries :: Python Modules"
    ],
    "description": "++++++++++++\npyfailmalloc\n++++++++++++\n\nDebug tool for Python injecting memory allocation faults to simulate a low\nmemory system to test how your application handles ``MemoryError`` exceptions.\n\npyfailmalloc is based on the `PEP 445\n<http://www.python.org/dev/peps/pep-0445/>`_ \"*Add new APIs to customize Python\nmemory allocators*\" and so requires at least Python 3.4.\n\n* `pyfailmalloc at the Python Cheeseshop (PyPI)\n  <http://pypi.python.org/pypi/pyfailmalloc>`_\n* `pyfailmalloc project at Bitbucket (source code)\n  <https://bitbucket.org/haypo/pyfailmalloc>`_\n\n\nAPI\n===\n\n* ``failmalloc.enable(range: int=1000)``: schedule a memory allocation failure\n  in random.randint(1, range) allocations.\n* ``failmalloc.disable()``: cancel the scheduled memory allocation failure\n\nThe version can be read from failmalloc.__version__ as a string (ex:\n``\"0.1\"``).\n\n\nChangelog\n=========\n\nVersion 0.2 (2015-01-27)\n\n- Support Python 3.5: hook also calloc(), support the new PyMemAllocatorEx API\n- Add tox.ini to run tests using tox\n\nVersion 0.1 (2013-07-08)\n\n- First public version\n\n\nSee also\n========\n\n* `failmalloc <http://www.nongnu.org/failmalloc/>`_\n* `pytracemalloc <http://pypi.python.org/pypi/pytracemalloc>`_",
    "docs_url": null,
    "download_url": "UNKNOWN",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://bitbucket.org/haypo/pyfailmalloc",
    "keywords": null,
    "license": "MIT license",
    "maintainer": null,
    "maintainer_email": null,
    "name": "pyfailmalloc",
    "platform": "UNKNOWN",
    "project_url": "https://pypi.org/project/pyfailmalloc/",
    "release_url": "https://pypi.org/project/pyfailmalloc/0.2/",
    "requires_python": null,
    "summary": "inject memory allocation faults",
    "version": "0.2"
  },
  "releases": {
    "0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "0eceee8f9ef32514c8b14f7696483c4f",
          "sha256": "f5f440b4dabc5c1e100891cf4f789a3561aebed29ff43a37d7199c5de75f6377"
        },
        "downloads": 2676,
        "filename": "pyfailmalloc-0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "0eceee8f9ef32514c8b14f7696483c4f",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3834,
        "upload_time": "2013-07-08T20:06:02",
        "url": "https://files.pythonhosted.org/packages/1e/c1/7dbbdd5635b0bbf282a618f0efeab1e509302047f702c0541b496a9498a5/pyfailmalloc-0.1.tar.gz"
      }
    ],
    "0.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "d73fa3893db61ddbda7c603a48a65c43",
          "sha256": "0ef885caf716d02d3dbc761e5ca5d3c354e364b36164a6b24316650360af0cb8"
        },
        "downloads": 1200,
        "filename": "pyfailmalloc-0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "d73fa3893db61ddbda7c603a48a65c43",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 10174,
        "upload_time": "2015-01-27T10:47:36",
        "url": "https://files.pythonhosted.org/packages/f9/38/59eab8f68019dc13220b9f485b1f690b25e4eacbe248fa617f675691b3d0/pyfailmalloc-0.2.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "d73fa3893db61ddbda7c603a48a65c43",
        "sha256": "0ef885caf716d02d3dbc761e5ca5d3c354e364b36164a6b24316650360af0cb8"
      },
      "downloads": 1200,
      "filename": "pyfailmalloc-0.2.tar.gz",
      "has_sig": false,
      "md5_digest": "d73fa3893db61ddbda7c603a48a65c43",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 10174,
      "upload_time": "2015-01-27T10:47:36",
      "url": "https://files.pythonhosted.org/packages/f9/38/59eab8f68019dc13220b9f485b1f690b25e4eacbe248fa617f675691b3d0/pyfailmalloc-0.2.tar.gz"
    }
  ]
}