{
  "info": {
    "author": "Ronald Oussoren",
    "author_email": "pyobjc-dev@lists.sourceforge.net",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Environment :: Console",
      "Environment :: MacOS X :: Cocoa",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Natural Language :: English",
      "Operating System :: MacOS :: MacOS X",
      "Programming Language :: Objective C",
      "Programming Language :: Python",
      "Programming Language :: Python :: 2",
      "Programming Language :: Python :: 2.7",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3.4",
      "Programming Language :: Python :: 3.5",
      "Programming Language :: Python :: Implementation :: CPython",
      "Topic :: Software Development :: Libraries :: Python Modules",
      "Topic :: Software Development :: User Interfaces"
    ],
    "description": "Wrappers for the \"ExceptionHandling\" framework on MacOSX. The ExceptionHandling\nframework provides facilities for monitoring and debugging exceptional\nconditions in Cocoa programs.\n\nPyObjC also provides low-level debugging utilities beyond the core\nExceptionHandling framework in the module ``PyObjCTools.Debugging``.\n\nThese wrappers don't include documentation, please check Apple's documention\nfor information on how to use this framework and PyObjC's documentation\nfor general tips and tricks regarding the translation between Python\nand (Objective-)C frameworks",
    "docs_url": "https://pythonhosted.org/pyobjc-framework-ExceptionHandling/",
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "http://pyobjc.sourceforge.net",
    "keywords": "PyObjC,ExceptionHandling",
    "license": "MIT License",
    "maintainer": "",
    "maintainer_email": "",
    "name": "pyobjc-framework-ExceptionHandling",
    "platform": "MacOS X",
    "project_url": "https://pypi.org/project/pyobjc-framework-ExceptionHandling/",
    "release_url": "https://pypi.org/project/pyobjc-framework-ExceptionHandling/3.2.1/",
    "requires_python": "",
    "summary": "Wrappers for the framework ExceptionHandling on Mac OS X",
    "version": "3.2.1"
  },
  "releases": {
    "2.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "a4f574ef58dfa357145676662f3eaed0",
          "sha256": "73af450a3f90972a8205ac19737444b4665a38e9520e54326d759729b77d3e3b"
        },
        "downloads": 5297,
        "filename": "pyobjc_framework_ExceptionHandling-2.2-py2.6.egg",
        "has_sig": false,
        "md5_digest": "a4f574ef58dfa357145676662f3eaed0",
        "packagetype": "bdist_egg",
        "python_version": "2.6",
        "size": 8010,
        "upload_time": "2009-11-24T16:06:25",
        "url": "https://files.pythonhosted.org/packages/b5/89/4aa65ceea7634c006855bdd7b1318375d35a20a27ebd0e23d83d5beb2531/pyobjc_framework_ExceptionHandling-2.2-py2.6.egg"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "fef4662cf6ddc5b6d30f738ef749b5bd",
          "sha256": "839ea74b9d5b99d8aa635b04185adce61eecf3df078fdef00e3bfde04fa0c60f"
        },
        "downloads": 5620,
        "filename": "pyobjc-framework-ExceptionHandling-2.2.tar.gz",
        "has_sig": false,
        "md5_digest": "fef4662cf6ddc5b6d30f738ef749b5bd",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 10501,
        "upload_time": "2009-11-24T16:06:25",
        "url": "https://files.pythonhosted.org/packages/79/df/1d5c72060da696bedee49e9fa92baf1809c0b93124fc73f0a34e69edc4a9/pyobjc-framework-ExceptionHandling-2.2.tar.gz"
      }
    ],
    "2.2b1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "3f396b3c684b18e9b257c05c010e3937",
          "sha256": "cabf1fbdfb50ab2bd03c0b758ee990cb36b8d7a766e4c1aaceb0ac247ddb37a8"
        },
        "downloads": 2980,
        "filename": "pyobjc-framework-ExceptionHandling-2.2b1.tar.gz",
        "has_sig": false,
        "md5_digest": "3f396b3c684b18e9b257c05c010e3937",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 9334,
        "upload_time": "2009-03-08T17:43:18",
        "url": "https://files.pythonhosted.org/packages/7a/d6/abfafa1a000862886c3f06d090c29663ca560b46d3e6e2eccaa4dc44f3ef/pyobjc-framework-ExceptionHandling-2.2b1.tar.gz"
      }
    ],
    "2.2b2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "6ddf6d44c5f8f9a237b5521bb9c45d31",
          "sha256": "5e94678ceccafd9cd4dbd7bb7df3797b346b92950f11bd95a1b901a100326070"
        },
        "downloads": 3217,
        "filename": "pyobjc_framework_ExceptionHandling-2.2b2-py2.6.egg",
        "has_sig": false,
        "md5_digest": "6ddf6d44c5f8f9a237b5521bb9c45d31",
        "packagetype": "bdist_egg",
        "python_version": "2.6",
        "size": 8005,
        "upload_time": "2009-05-26T11:46:20",
        "url": "https://files.pythonhosted.org/packages/20/7d/2841513704ac6b32c3e2ee85a638f94133fdccd5f8782e8bfd40f4d80e3d/pyobjc_framework_ExceptionHandling-2.2b2-py2.6.egg"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "c4052aa09e06ec13b8852311fdc3495d",
          "sha256": "d695afbcab18c5f65096212c7da9efee6ff797a9949930095682451be0c12b75"
        },
        "downloads": 3010,
        "filename": "pyobjc-framework-ExceptionHandling-2.2b2.tar.gz",
        "has_sig": false,
        "md5_digest": "c4052aa09e06ec13b8852311fdc3495d",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 9453,
        "upload_time": "2009-05-26T11:46:20",
        "url": "https://files.pythonhosted.org/packages/4e/17/28f231665c02c1d947dc43885f1285399bdacb653e8fb11f0b3b0d4207f7/pyobjc-framework-ExceptionHandling-2.2b2.tar.gz"
      }
    ],
    "2.3": [
      {
        "comment_text": "",
        "digests": {
          "md5": "f46706f9d1316a044404026e848863aa",
          "sha256": "7308be6826ad7ea16a13cd01dbcc916f0456cec1709e5cd75340a6101e014070"
        },
        "downloads": 3022,
        "filename": "pyobjc_framework_ExceptionHandling-2.3-py2.6.egg",
        "has_sig": false,
        "md5_digest": "f46706f9d1316a044404026e848863aa",
        "packagetype": "bdist_egg",
        "python_version": "2.6",
        "size": 8016,
        "upload_time": "2010-07-29T19:49:24",
        "url": "https://files.pythonhosted.org/packages/09/3e/5dd689e10695d0f610e2e3c82db897a3cc14e5e2f6aa859730883e461d34/pyobjc_framework_ExceptionHandling-2.3-py2.6.egg"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "d2dc230db3a5d8bc1bc60b71a16f6dbd",
          "sha256": "bdc7838f16ee87cfc78be864e0323f6d196309b869bc6f52bca06a750a3f3ff6"
        },
        "downloads": 5821,
        "filename": "pyobjc_framework_ExceptionHandling-2.3-py2.7.egg",
        "has_sig": false,
        "md5_digest": "d2dc230db3a5d8bc1bc60b71a16f6dbd",
        "packagetype": "bdist_egg",
        "python_version": "2.7",
        "size": 7998,
        "upload_time": "2010-07-29T19:49:26",
        "url": "https://files.pythonhosted.org/packages/54/ad/caf67dd09612d23061fa2119a0592f1eab68cd91b6ca26fc998c5e249505/pyobjc_framework_ExceptionHandling-2.3-py2.7.egg"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "522c9bc94a9bfe11c9340080d44c0107",
          "sha256": "c952a744930a0935257089cd9957dd552c443841a2bd0da4c1a569018f51cdaf"
        },
        "downloads": 3107,
        "filename": "pyobjc_framework_ExceptionHandling-2.3-py3.1.egg",
        "has_sig": false,
        "md5_digest": "522c9bc94a9bfe11c9340080d44c0107",
        "packagetype": "bdist_egg",
        "python_version": "3.1",
        "size": 8074,
        "upload_time": "2010-07-29T19:49:30",
        "url": "https://files.pythonhosted.org/packages/bc/0c/368371294f1e3768e9bdcc2dc85cbbd778bbc268bf339c614e8e6a2da2a7/pyobjc_framework_ExceptionHandling-2.3-py3.1.egg"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "93e25296d792a4dd3b72daf6b197997f",
          "sha256": "b116f17de96dd1a7a20c86db25e621ddf1b06220e0340269269dbf4724600408"
        },
        "downloads": 2984,
        "filename": "pyobjc_framework_ExceptionHandling-2.3-py3.2.egg",
        "has_sig": false,
        "md5_digest": "93e25296d792a4dd3b72daf6b197997f",
        "packagetype": "bdist_egg",
        "python_version": "3.2",
        "size": 8077,
        "upload_time": "2010-07-29T19:49:33",
        "url": "https://files.pythonhosted.org/packages/d4/2a/f0b0d7e480e5c0978fc0b73ed4a33631a28ed81a32d258a338b28b41fb40/pyobjc_framework_ExceptionHandling-2.3-py3.2.egg"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "c35e2894567c0cdd5d4ecb424ffbc518",
          "sha256": "3dd39543eb8639267cb3cb02685b159744bf10ea733a104d4c8a1554b96952b5"
        },
        "downloads": 3092,
        "filename": "pyobjc-framework-ExceptionHandling-2.3.tar.gz",
        "has_sig": false,
        "md5_digest": "c35e2894567c0cdd5d4ecb424ffbc518",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 15853,
        "upload_time": "2010-07-29T19:49:23",
        "url": "https://files.pythonhosted.org/packages/22/fe/7ae2cdffd55b33274faea7e7e97ac8614e65306233c93b00e9706246ba4d/pyobjc-framework-ExceptionHandling-2.3.tar.gz"
      }
    ],
    "2.4": [
      {
        "comment_text": "",
        "digests": {
          "md5": "676835c7b68f5e9e2293e9839767298c",
          "sha256": "a09cab7654b4ec76349c55761efdb0225e6a00018622a82a394b4b45f54166dc"
        },
        "downloads": 3164,
        "filename": "pyobjc-framework-ExceptionHandling-2.4.tar.gz",
        "has_sig": false,
        "md5_digest": "676835c7b68f5e9e2293e9839767298c",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 17593,
        "upload_time": "2012-11-01T08:46:23",
        "url": "https://files.pythonhosted.org/packages/e9/c8/6077eeb24fe79f97c9f33aa342fa13dffb3c7f4fc6558c87ba04f08756b8/pyobjc-framework-ExceptionHandling-2.4.tar.gz"
      }
    ],
    "2.5.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "abf7c6fd065d26d4ab8674dd2871a0df",
          "sha256": "fa943afe83357a514834cab5a99af8db77d18817f79414032da90656a7f08281"
        },
        "downloads": 15034,
        "filename": "pyobjc-framework-ExceptionHandling-2.5.1.tar.gz",
        "has_sig": false,
        "md5_digest": "abf7c6fd065d26d4ab8674dd2871a0df",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 14431,
        "upload_time": "2013-01-22T19:18:51",
        "url": "https://files.pythonhosted.org/packages/82/2c/135c86b68f487aea34191123e6ae08fad54d389b9908f76394d49210d2c2/pyobjc-framework-ExceptionHandling-2.5.1.tar.gz"
      }
    ],
    "3.0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "e399de5ea48fc454c07c1948a2bf77db",
          "sha256": "c25e33170cc5c5e02e78d8336db80c592eeae2aaef81bfc8e11b5cfc892bb96d"
        },
        "downloads": 5462,
        "filename": "pyobjc-framework-ExceptionHandling-3.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "e399de5ea48fc454c07c1948a2bf77db",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 13344,
        "upload_time": "2014-07-27T08:48:18",
        "url": "https://files.pythonhosted.org/packages/15/c8/12ff4491e585297898c4edc88eeabe408c17916fe31b444c8c82314d3d46/pyobjc-framework-ExceptionHandling-3.0.1.tar.gz"
      }
    ],
    "3.0.3": [
      {
        "comment_text": "",
        "digests": {
          "md5": "a36c6feace083032f64e9508ff565f3e",
          "sha256": "9325a62a56216f6ffdd5bacef1d125c56d7805a2e89343eab52163a3e7327ce2"
        },
        "downloads": 2640,
        "filename": "pyobjc-framework-ExceptionHandling-3.0.3.tar.gz",
        "has_sig": false,
        "md5_digest": "a36c6feace083032f64e9508ff565f3e",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 13379,
        "upload_time": "2014-10-22T15:11:03",
        "url": "https://files.pythonhosted.org/packages/d3/48/388954e938b3e545a47b4a8ca0c41fee6006877a8caf99e94453b25c3b3d/pyobjc-framework-ExceptionHandling-3.0.3.tar.gz"
      }
    ],
    "3.0.4": [
      {
        "comment_text": "",
        "digests": {
          "md5": "ffcd0ece60bf49458076b80fcdb7af79",
          "sha256": "ccc5a85dd3aa00196c5087090bec1a1cf458387a6538ab654a62bf5e2ac93e89"
        },
        "downloads": 16905,
        "filename": "pyobjc-framework-ExceptionHandling-3.0.4.tar.gz",
        "has_sig": false,
        "md5_digest": "ffcd0ece60bf49458076b80fcdb7af79",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 13384,
        "upload_time": "2014-12-07T23:20:46",
        "url": "https://files.pythonhosted.org/packages/85/ec/b13e3464d9bb4d3a6ad1ebe25b66bb9a1e7c2b2df68858a9df0a4f379546/pyobjc-framework-ExceptionHandling-3.0.4.tar.gz"
      }
    ],
    "3.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "fc52011828a776164721be7422fde5e0",
          "sha256": "76c571c5f44809f6fcebbdde2484359a14d61f92931257a3a6816c468115f73f"
        },
        "downloads": 115,
        "filename": "pyobjc-framework-ExceptionHandling-3.1.tar.gz",
        "has_sig": false,
        "md5_digest": "fc52011828a776164721be7422fde5e0",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 13392,
        "upload_time": "2016-03-28T09:51:42",
        "url": "https://files.pythonhosted.org/packages/0c/ac/5fa234422fcca9d5512bf18cc40bac30cf451a47a5841de8c16acf209518/pyobjc-framework-ExceptionHandling-3.1.tar.gz"
      }
    ],
    "3.1.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "c670c0f3fbec6f60cbf94f6d65fa54d4",
          "sha256": "f8e18cb7f2a0bde38d3c36736645826f66c5fe3c738eeed8ba366dbe520c825f"
        },
        "downloads": 2765,
        "filename": "pyobjc-framework-ExceptionHandling-3.1.1.tar.gz",
        "has_sig": false,
        "md5_digest": "c670c0f3fbec6f60cbf94f6d65fa54d4",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 13572,
        "upload_time": "2016-03-28T10:48:19",
        "url": "https://files.pythonhosted.org/packages/2b/91/8d46c724b8248d0f9c6accb4423c1fb4666b8dc60b371d7e7ff34313b901/pyobjc-framework-ExceptionHandling-3.1.1.tar.gz"
      }
    ],
    "3.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "3acf444a115b406862c84f4235ed7cce",
          "sha256": "54dfeb36c607c47d96d88971a82e58537b56b205263c5556058a4c375e92cd6e"
        },
        "downloads": 43,
        "filename": "pyobjc-framework-ExceptionHandling-3.2.tar.gz",
        "has_sig": false,
        "md5_digest": "3acf444a115b406862c84f4235ed7cce",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 13921,
        "upload_time": "2016-12-06T16:03:22",
        "url": "https://files.pythonhosted.org/packages/57/f6/09675c0d32dd6cd416fbdcdd755db0c0d5e92d5d186438ff67c914d0f285/pyobjc-framework-ExceptionHandling-3.2.tar.gz"
      }
    ],
    "3.2.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "86710399463bc2e8d58cb6c2ed351d7e",
          "sha256": "ee2532c12d739a6c191a6ac0a3cb34c39bd6b3208f912d4cc3d662abc7d6c1fd"
        },
        "downloads": 1459,
        "filename": "pyobjc_framework_ExceptionHandling-3.2.1-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "86710399463bc2e8d58cb6c2ed351d7e",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 7428,
        "upload_time": "2016-12-12T10:24:49",
        "url": "https://files.pythonhosted.org/packages/02/bb/2aacc995486d7901cbc8653e10755f5560d41561ec6776223d19a5a8a5d5/pyobjc_framework_ExceptionHandling-3.2.1-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "47861232d6009600261513c80a756f01",
          "sha256": "cdeb5a4be0e44cb5b6c0d84cb27568853737b1d232fe717cebfec3883815129a"
        },
        "downloads": 115,
        "filename": "pyobjc-framework-ExceptionHandling-3.2.1.tar.gz",
        "has_sig": false,
        "md5_digest": "47861232d6009600261513c80a756f01",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 13987,
        "upload_time": "2016-12-12T10:36:25",
        "url": "https://files.pythonhosted.org/packages/54/97/40944c18c0e3ef7d660f4bd2bf3f0695ce77ea54c49fa6ff981d5a00c3f9/pyobjc-framework-ExceptionHandling-3.2.1.tar.gz"
      }
    ],
    "3.2.1b1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "f2b3b87cf3c06f90b363c85448e8c4ec",
          "sha256": "a96205c3610d8769ae4a8706e1a8a348041b8e380aa98eb3c0fad2e7190c3645"
        },
        "downloads": 55,
        "filename": "pyobjc_framework_ExceptionHandling-3.2.1b1-py2.py3-none-any.whl",
        "has_sig": false,
        "md5_digest": "f2b3b87cf3c06f90b363c85448e8c4ec",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 7468,
        "upload_time": "2016-12-12T09:11:29",
        "url": "https://files.pythonhosted.org/packages/ca/3a/e876dc93a1a7ff96420bc14b86d069c9ecf0bc5b6fe7d6c87d13b0308680/pyobjc_framework_ExceptionHandling-3.2.1b1-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "160e66852a416f6097270f29140d1c51",
          "sha256": "7349a45e7d7877022e443892b92402c67fb90c742e0a73520ecff93292650c27"
        },
        "downloads": 64,
        "filename": "pyobjc-framework-ExceptionHandling-3.2.1b1.tar.gz",
        "has_sig": false,
        "md5_digest": "160e66852a416f6097270f29140d1c51",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 13997,
        "upload_time": "2016-12-12T09:17:45",
        "url": "https://files.pythonhosted.org/packages/51/8f/60ec7645a52b1dcddb33a09b2adf14a6043150e54d4302b14a9772f7c581/pyobjc-framework-ExceptionHandling-3.2.1b1.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "86710399463bc2e8d58cb6c2ed351d7e",
        "sha256": "ee2532c12d739a6c191a6ac0a3cb34c39bd6b3208f912d4cc3d662abc7d6c1fd"
      },
      "downloads": 1459,
      "filename": "pyobjc_framework_ExceptionHandling-3.2.1-py2.py3-none-any.whl",
      "has_sig": false,
      "md5_digest": "86710399463bc2e8d58cb6c2ed351d7e",
      "packagetype": "bdist_wheel",
      "python_version": "py2.py3",
      "size": 7428,
      "upload_time": "2016-12-12T10:24:49",
      "url": "https://files.pythonhosted.org/packages/02/bb/2aacc995486d7901cbc8653e10755f5560d41561ec6776223d19a5a8a5d5/pyobjc_framework_ExceptionHandling-3.2.1-py2.py3-none-any.whl"
    },
    {
      "comment_text": "",
      "digests": {
        "md5": "47861232d6009600261513c80a756f01",
        "sha256": "cdeb5a4be0e44cb5b6c0d84cb27568853737b1d232fe717cebfec3883815129a"
      },
      "downloads": 115,
      "filename": "pyobjc-framework-ExceptionHandling-3.2.1.tar.gz",
      "has_sig": false,
      "md5_digest": "47861232d6009600261513c80a756f01",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 13987,
      "upload_time": "2016-12-12T10:36:25",
      "url": "https://files.pythonhosted.org/packages/54/97/40944c18c0e3ef7d660f4bd2bf3f0695ce77ea54c49fa6ff981d5a00c3f9/pyobjc-framework-ExceptionHandling-3.2.1.tar.gz"
    }
  ]
}