{
  "info": {
    "author": "Huang Jiangbin",
    "author_email": "dobetter@zencore.cn",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: MIT License",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3 :: Only",
      "Topic :: Software Development :: Libraries :: Python Modules"
    ],
    "description": "zenore-errors\n=============\n\n.. image:: https://travis-ci.org/zencore-dobetter/zencore-errors.svg?branch=master\n    :target: https://travis-ci.org/zencore-dobetter/zencore-errors\n\nZencore error code collection.\n\n\n",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "https://github.com/zencore-dobetter/zencore-errors",
    "keywords": "zencore-errors",
    "license": "MIT",
    "maintainer": "",
    "maintainer_email": "",
    "name": "zencore-errors",
    "platform": "",
    "project_url": "https://pypi.org/project/zencore-errors/",
    "release_url": "https://pypi.org/project/zencore-errors/2.0.19/",
    "requires_dist": [],
    "requires_python": "",
    "summary": "Zencore error code collection",
    "version": "2.0.19"
  },
  "releases": {
    "1.0.4": [
      {
        "comment_text": "",
        "digests": {
          "md5": "f22824df67da7137c4565e3595f27fd4",
          "sha256": "ee15e8d03bb626560b183c1a30e12013c0458f5d93da44d440fe4c305be14e1b"
        },
        "downloads": -1,
        "filename": "zencore-errors-1.0.4.tar.gz",
        "has_sig": false,
        "md5_digest": "f22824df67da7137c4565e3595f27fd4",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2253,
        "upload_time": "2017-08-10T14:04:23",
        "url": "https://files.pythonhosted.org/packages/d0/23/e7f1efe3ed3befcf9a144e83f76b668b5addfab9198d7a01dcbf2ca6711c/zencore-errors-1.0.4.tar.gz"
      }
    ],
    "1.0.5": [
      {
        "comment_text": "",
        "digests": {
          "md5": "9df49a4be92747ea5563e7e9c9a0d986",
          "sha256": "12fb7da61d8a4272dcbae9f00fc18969d3d918c408e389ae7cb02e69bb34c65f"
        },
        "downloads": -1,
        "filename": "zencore-errors-1.0.5.tar.gz",
        "has_sig": false,
        "md5_digest": "9df49a4be92747ea5563e7e9c9a0d986",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 2274,
        "upload_time": "2017-09-18T14:52:19",
        "url": "https://files.pythonhosted.org/packages/b9/3f/79f5ec67323d44f29e46458711d88ac996ebdd451b6b9d666dd3322cbcfa/zencore-errors-1.0.5.tar.gz"
      }
    ],
    "2.0.14": [
      {
        "comment_text": "",
        "digests": {
          "md5": "9c3ee24b191f051f19b6b87498f608fd",
          "sha256": "36de398fdf02551c59c3575e155c41ef718e508b7847f51ab1961ab991dde97e"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.14.tar.gz",
        "has_sig": false,
        "md5_digest": "9c3ee24b191f051f19b6b87498f608fd",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3696,
        "upload_time": "2017-10-31T14:44:03",
        "url": "https://files.pythonhosted.org/packages/ab/7c/85cebfffdf3b9164d572931859c4319e145185558db6204084446bf549ec/zencore-errors-2.0.14.tar.gz"
      }
    ],
    "2.0.15": [
      {
        "comment_text": "",
        "digests": {
          "md5": "4c2e63aabcaf820d3e2c3adcf0560853",
          "sha256": "8b95e99f217dc07ec975fc254b708cf01800e99a52ace5dcea6ae554df32e12b"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.15.tar.gz",
        "has_sig": false,
        "md5_digest": "4c2e63aabcaf820d3e2c3adcf0560853",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3736,
        "upload_time": "2017-11-07T02:17:34",
        "url": "https://files.pythonhosted.org/packages/dc/87/c5deacc003f0587021eff4dc49015362441d96ab52689ec3df15d27c4cdd/zencore-errors-2.0.15.tar.gz"
      }
    ],
    "2.0.16": [
      {
        "comment_text": "",
        "digests": {
          "md5": "5cc23bd5abcad411a157ff16b33a66e1",
          "sha256": "a0b170f128575a411fd877119f8aac5bddc7ebc2131e4e77cd94bdcc2305ee2c"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.16.tar.gz",
        "has_sig": false,
        "md5_digest": "5cc23bd5abcad411a157ff16b33a66e1",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3774,
        "upload_time": "2017-11-07T03:12:42",
        "url": "https://files.pythonhosted.org/packages/ec/0b/d5bb743199541de527a3b5ffe382f482648aa6bac37be30e6f2fe72d0412/zencore-errors-2.0.16.tar.gz"
      }
    ],
    "2.0.17": [
      {
        "comment_text": "",
        "digests": {
          "md5": "6c18495520c496cad0df99a9ff56b975",
          "sha256": "35f6a3808b548abd4980bb60dc2d4cbb5829e8d5718941402dac9ecdf05700f7"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.17.tar.gz",
        "has_sig": false,
        "md5_digest": "6c18495520c496cad0df99a9ff56b975",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 3806,
        "upload_time": "2017-11-07T06:34:34",
        "url": "https://files.pythonhosted.org/packages/a1/34/0073b9fb78e31f244b2fc63e3750811c2897f50fc4134ade91a3e28e9c2e/zencore-errors-2.0.17.tar.gz"
      }
    ],
    "2.0.18": [
      {
        "comment_text": "",
        "digests": {
          "md5": "3091e922acff8b509ade9419caed4b94",
          "sha256": "5e7681627cb80a5ebdb7103fee4595d966911e25f50afa27bbd1095670f74f7a"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.18.tar.gz",
        "has_sig": false,
        "md5_digest": "3091e922acff8b509ade9419caed4b94",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 4052,
        "upload_time": "2017-11-08T06:53:08",
        "url": "https://files.pythonhosted.org/packages/a7/5a/76ce4644c2759671aa23b21c532bccb1a6b3f584aebccba94f0a2ab52a87/zencore-errors-2.0.18.tar.gz"
      }
    ],
    "2.0.19": [
      {
        "comment_text": "",
        "digests": {
          "md5": "2565959eb83378f2492df31306fc03a0",
          "sha256": "91cdf0b277624eddb466b94911eb689c654f06873038fe724f4deac1aae7747c"
        },
        "downloads": -1,
        "filename": "zencore-errors-2.0.19.tar.gz",
        "has_sig": false,
        "md5_digest": "2565959eb83378f2492df31306fc03a0",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 4110,
        "upload_time": "2017-11-24T15:58:09",
        "url": "https://files.pythonhosted.org/packages/39/ef/7aa3806c59eaab2e1ae07f708819679157345c5157f83e0ed1f641ea9c47/zencore-errors-2.0.19.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "2565959eb83378f2492df31306fc03a0",
        "sha256": "91cdf0b277624eddb466b94911eb689c654f06873038fe724f4deac1aae7747c"
      },
      "downloads": -1,
      "filename": "zencore-errors-2.0.19.tar.gz",
      "has_sig": false,
      "md5_digest": "2565959eb83378f2492df31306fc03a0",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 4110,
      "upload_time": "2017-11-24T15:58:09",
      "url": "https://files.pythonhosted.org/packages/39/ef/7aa3806c59eaab2e1ae07f708819679157345c5157f83e0ed1f641ea9c47/zencore-errors-2.0.19.tar.gz"
    }
  ]
}