{
  "info": {
    "author": "Zope Foundation and Contributors",
    "author_email": "zope-dev@zope.org",
    "bugtrack_url": null,
    "classifiers": [
      "Development Status :: 5 - Production/Stable",
      "Environment :: Web Environment",
      "Framework :: Zope3",
      "Intended Audience :: Developers",
      "License :: OSI Approved :: Zope Public License",
      "Natural Language :: English",
      "Operating System :: OS Independent",
      "Programming Language :: Python",
      "Programming Language :: Python :: 2",
      "Programming Language :: Python :: 2.7",
      "Programming Language :: Python :: 3",
      "Programming Language :: Python :: 3.3",
      "Programming Language :: Python :: 3.4",
      "Programming Language :: Python :: 3.5",
      "Programming Language :: Python :: Implementation :: CPython",
      "Programming Language :: Python :: Implementation :: PyPy",
      "Topic :: Internet :: WWW/HTTP"
    ],
    "description": "``zope.exceptions``\n===================\n\n.. image:: https://img.shields.io/pypi/v/zope.exceptions.svg\n    :target: https://pypi.python.org/pypi/zope.exceptions/\n    :alt: Latest Version\n\n.. image:: https://travis-ci.org/zopefoundation/zope.exceptions.png?branch=master\n        :target: https://travis-ci.org/zopefoundation/zope.exceptions\n\n.. image:: https://readthedocs.org/projects/zopeexceptions/badge/?version=latest\n        :target: http://zopeexceptions.readthedocs.org/en/latest/\n        :alt: Documentation Status\n\nThis package contains exception exceptions and implementations which are so\ngeneral purpose that they don't belong in Zope application-specific packages.\n\nPlease see http://docs.zope.org/zope.exceptions/ for the documentation.\n\n\n``zope.exceptions`` Changelog\n=============================\n\n4.1.0 (2017-04-12)\n------------------\n\n- Drop support for Python 2.6 and 3.2.\n\n- Make ``exceptionformatter.extract_stack`` signature comply with\n  ``traceback.extract_stack``\n\n- Add support for Python 3.5.\n\n4.0.8 (2015-08-13)\n------------------\n\n- Fixes around ``TextExceptionFormatter`` ``limit``: ``formatException``\n  and ``extractStack`` was cutting the traceback at the bottom,\n  at the most interesting point. Now it will cut from the middle.\n  Some text about the missing entries will be inserted.\n\n- Maybe fix for ``extractStack``, it did not detect recursions in the frames.\n\n4.0.7 (2014-03-19)\n------------------\n\n- Added explicit support for Python 3.4.\n\n- Updated ``boostrap.py`` to version 2.2.\n\n\n4.0.6 (2013-02-28)\n------------------\n\n- Make sure that ``setup.py`` finds all tests. Now tox runs them all as well.\n\n- Fix failing test under Python 3.\n\n- Made buildout work under Python 3 and Buildout 2.\n\n\n4.0.5 (2012-12-31)\n------------------\n\n- Fleshed out PyPI Trove classifiers.\n\n- Fixed a test failure under Python 2.6.\n\n\n4.0.4 (2012-12-13)\n------------------\n\n- Release with a fixed MANIFEST.in (without ``docs/``)\n\n\n4.0.3 (2012-12-10)\n------------------\n\n- Fixed format_exception(..., as_html=True) not to HTML-escape the '<br />'\n  it adds to the exception value.\n\n\n4.0.2 (2012-11-21)\n------------------\n\n- Test Python 3.3 support under tox.\n\n\n4.0.1 (2012-08-20)\n------------------\n\n- Fixed optional dependency code for `zope.security` to work under Python 3.3.\n\n\n4.0.0.1 (2012-05-16)\n--------------------\n\n- Fixed rendering of package docs on PyPI.\n\n\n4.0.0 (2012-05-16)\n------------------\n\n- Automated build of Sphinx HTML docs and running doctest snippets via tox.\n\n- Added Sphinx documentation.\n\n- Added support for continuous integration using ``tox`` and ``jenkins``.\n\n- Removed use of '2to3' and associated fixers when installing under Py3k.\n  The code is now in a \"compatible subset\" which supports Python 2.6, 2.7,\n  and 3.2, including PyPy 1.8 (the version compatible with the 2.7 language\n  spec).\n\n- 100% unit test coverage.\n\n- Dropped explicit support for Python 2.4 / 2.5 / 3.1.\n\n- Added 'setup.py dev' alias (runs ``setup.py develop`` plus installs\n  ``nose`` and ``coverage``).\n\n- Added 'setup.py docs' alias (installs ``Sphinx`` and dependencies).\n\n\n3.7.1 (2012-03-28)\n------------------\n\n- Fix: missed to reverse extractStack entries\n\n\n3.7.0 (2012-03-28)\n------------------\n\n- Added TextExceptionFormatter.extractStack and extract_stack\n\n\n3.6.2 (2012-03-28)\n------------------\n\n- Fallback to traceback.format_tb when the formatter is called recursively.\n  i.e. Don't let errors in the formatter pass silently.\n\n- Fix deprecated unittest functions: ``assert_`` and ``assertEquals``.\n\n3.6.1 (2010-07-06)\n------------------\n\n- Fixed tests to work under Python 2.7.\n\n- PEP8 cleanup and removed obsolete build infrastructure files.\n\n\n3.6.0 (2010-05-02)\n------------------\n\n- Added support to bootstrap on Jython.\n\n- Added Python 3 support.\n\n- The dependency on zope.testing seemed spurious, possibly a rest of a real\n  dependency that is gone now. I removed it.\n\n\n3.5.2 (2008-04-30)\n------------------\n\n- Updated CHANGES.txt.\n\n\n3.5.1 (2008-04-28)\n------------------\n\n- Reverted changes in 3.5.0.\n\n\n3.5.0\n-----\n\n- Added the capability for exceptions to be formatted line-by-line.\n  Unfortunately, also introduced a bug cause each line of the exception to be\n  its own log message.\n\n\n3.4.0 (2007-10-02)\n------------------\n\n- Updated package meta-data.\n\n\n3.4.0b2 (2007-08-14)\n--------------------\n\n- Removed superfluous dependency on ``zope.deprecation``.\n\n\n3.4.0b1 (2007-07-09)\n--------------------\n\n- Corresponds to the version of the ``zope.exceptions`` package shipped as\n  part of the Zope 3.4.0b1 release.\n\n\n3.2.0 (2006-01-05)\n------------------\n\n- Corresponds to the version of the ``zope.exceptions`` package shipped as part of\n  the Zope 3.2.0 release.\n\n- Deprecated the ``INotFoundError`` interface and the corresponding\n  ``NotFoundError`` exception class, in favor of \"standard\" exceptions\n  ``AttributeError``, ``KeyError``).  The deprecated items will be removed in\n  Zope 3.3.\n\n\n3.0.0 (2004-11-07)\n------------------\n\n- Corresponds to the version of the zope.exceptions package shipped as part of\n  the Zope X3.0.0 release.",
    "docs_url": null,
    "download_url": "",
    "downloads": {
      "last_day": 0,
      "last_month": 0,
      "last_week": 0
    },
    "home_page": "http://cheeseshop.python.org/pypi/zope.exceptions",
    "keywords": "zope exceptions",
    "license": "ZPL 2.1",
    "maintainer": "",
    "maintainer_email": "",
    "name": "zope.exceptions",
    "platform": "",
    "project_url": "https://pypi.org/project/zope.exceptions/",
    "release_url": "https://pypi.org/project/zope.exceptions/4.1.0/",
    "requires_python": "",
    "summary": "Zope Exceptions",
    "version": "4.1.0"
  },
  "releases": {
    "3.4.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "d51478ee1531a0007f1a0cedea431fb3",
          "sha256": "497850c66f0a0cd1dadddd8e6db22ee6bc1fc8b1d0637c8a8ccb217c900de39f"
        },
        "downloads": 36086,
        "filename": "zope.exceptions-3.4.0.tar.gz",
        "has_sig": false,
        "md5_digest": "d51478ee1531a0007f1a0cedea431fb3",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 7757,
        "upload_time": "2007-10-02T13:49:02",
        "url": "https://files.pythonhosted.org/packages/9a/0a/bc0d8289c17917a8c34cda4b3dcf944cb37c6476a3a634c6c697712030c8/zope.exceptions-3.4.0.tar.gz"
      }
    ],
    "3.4dev": [
      {
        "comment_text": "",
        "digests": {
          "md5": "b0410ce7a47b108011c6cfcf1e7b7716",
          "sha256": "01b4cb64999daca51f2a8994bf6dde7bbef221e6d4b902a9b2804401e95ed8aa"
        },
        "downloads": 5056,
        "filename": "zope.exceptions-3.4dev-r73107.tar.gz",
        "has_sig": false,
        "md5_digest": "b0410ce7a47b108011c6cfcf1e7b7716",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 7295,
        "upload_time": "2007-03-16T06:00:20",
        "url": "https://files.pythonhosted.org/packages/45/d0/cb9012118410142830b0bf3d38a560155d08c7bd34fb954638a18bd68da9/zope.exceptions-3.4dev-r73107.tar.gz"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "42bf032508b8f52c6a0df4bb30928fe3",
          "sha256": "c39f4988fbc9edd3bf3e03f5bb098c0c62719611f2e09a0477cc30bb3c8e7240"
        },
        "downloads": 3058,
        "filename": "zope.exceptions-3.4dev.tar.gz",
        "has_sig": false,
        "md5_digest": "42bf032508b8f52c6a0df4bb30928fe3",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 7259,
        "upload_time": "2007-04-23T14:08:09",
        "url": "https://files.pythonhosted.org/packages/49/55/8db29c11897036d889307a10c879bfb51f3cadc3665de859f6414e28d2f4/zope.exceptions-3.4dev.tar.gz"
      }
    ],
    "3.5.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "85b4865e8de5a6c9201716002e576fac",
          "sha256": "43b726d8fe2e06189c13e1fd977b3e0c3e476d3836d0787335e56436418e5cd6"
        },
        "downloads": 12303,
        "filename": "zope.exceptions-3.5.0.tar.gz",
        "has_sig": false,
        "md5_digest": "85b4865e8de5a6c9201716002e576fac",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 9277,
        "upload_time": "2008-01-22T17:08:17",
        "url": "https://files.pythonhosted.org/packages/82/46/24c869fa48821cd2b113830d329acb83a4149cbcdefdab179694a6176151/zope.exceptions-3.5.0.tar.gz"
      }
    ],
    "3.5.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "224860847b1a97c4ae92244b6a053a9e",
          "sha256": "4eac1bb65e4548f815b04c07011561aa4e57187cb31f7c3ca24b3d81aca7416d"
        },
        "downloads": 3077,
        "filename": "zope.exceptions-3.5.1.tar.gz",
        "has_sig": false,
        "md5_digest": "224860847b1a97c4ae92244b6a053a9e",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 8463,
        "upload_time": "2008-04-28T15:01:05",
        "url": "https://files.pythonhosted.org/packages/d4/9c/357e23099b0297078fbfc256c22da9a5d9d6dfb5aa6d65e59697ad0148aa/zope.exceptions-3.5.1.tar.gz"
      }
    ],
    "3.5.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "13172baeb3182af15149cdbf94a5380b",
          "sha256": "cd7b0abd38d654d5905d62b867641ef2d19740831d00704bc4c534ab9fc28390"
        },
        "downloads": 86945,
        "filename": "zope.exceptions-3.5.2.tar.gz",
        "has_sig": false,
        "md5_digest": "13172baeb3182af15149cdbf94a5380b",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 8767,
        "upload_time": "2008-04-30T15:55:08",
        "url": "https://files.pythonhosted.org/packages/3e/2b/5d4f7e37e73ef86defba6502c3190b40e9ef2247e2c9691c9832e3c4bd41/zope.exceptions-3.5.2.tar.gz"
      }
    ],
    "3.6.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "491779b577a49f547982ff39b3903b1a",
          "sha256": "4ad8604f944dc51ae21b1f398f69ce236de2dcec1ebb1c2ee230873d52ea9002"
        },
        "downloads": 9442,
        "filename": "zope.exceptions-3.6.0.tar.gz",
        "has_sig": false,
        "md5_digest": "491779b577a49f547982ff39b3903b1a",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 9713,
        "upload_time": "2010-05-02T23:12:40",
        "url": "https://files.pythonhosted.org/packages/d6/a4/1cba5fd50739c660d1bc2e12cd27d9e2c06d6fe648dd54d9d1c20b627ed9/zope.exceptions-3.6.0.tar.gz"
      }
    ],
    "3.6.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "b735a62e1ef16e746764b4938a4d7926",
          "sha256": "a6d0c50f8103b2e89bc6c606fe97ed84b0cbe09e08b8a537a8909ab712fbf3e6"
        },
        "downloads": 90383,
        "filename": "zope.exceptions-3.6.1.zip",
        "has_sig": false,
        "md5_digest": "b735a62e1ef16e746764b4938a4d7926",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 17881,
        "upload_time": "2010-07-06T19:34:33",
        "url": "https://files.pythonhosted.org/packages/36/ff/1792a6dbc8e8f88ea21d70b53fdc3f690118ea10a0462ecb9efc7024b524/zope.exceptions-3.6.1.zip"
      }
    ],
    "3.6.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "d7234d99d728abe3d9275346e8d24fd9",
          "sha256": "ba8618991341ead4b726bf7b8b9e5bbb47018f29c9923412c272b27e440c6ac5"
        },
        "downloads": 99663,
        "filename": "zope.exceptions-3.6.2.tar.gz",
        "has_sig": false,
        "md5_digest": "d7234d99d728abe3d9275346e8d24fd9",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 9830,
        "upload_time": "2012-03-28T15:54:52",
        "url": "https://files.pythonhosted.org/packages/01/03/3f240e293811e547b1adb6e2f3e3ad1412a6a125abaef21a517172e68595/zope.exceptions-3.6.2.tar.gz"
      }
    ],
    "3.7.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "c0a845c15d8e42fea984b3fda92526ca",
          "sha256": "531e9aae5cf88598de88df549d3f9708a83c142f06dddf2117c5c9e8b35b3ce7"
        },
        "downloads": 2496,
        "filename": "zope.exceptions-3.7.0.tar.gz",
        "has_sig": false,
        "md5_digest": "c0a845c15d8e42fea984b3fda92526ca",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 10119,
        "upload_time": "2012-03-28T16:06:40",
        "url": "https://files.pythonhosted.org/packages/a7/63/9c0de0b732b7d9d0785411e1449b3a4167c3eb36bcd80e1d7839a187b8be/zope.exceptions-3.7.0.tar.gz"
      }
    ],
    "3.7.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "ec7876e69279a919d58d48d4852fa9e3",
          "sha256": "f2c555ffc35aa503471d6200472a66dfed5fd54d38095f555aac6e1a09f80fa3"
        },
        "downloads": 6757,
        "filename": "zope.exceptions-3.7.1.tar.gz",
        "has_sig": false,
        "md5_digest": "ec7876e69279a919d58d48d4852fa9e3",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 10160,
        "upload_time": "2012-03-28T16:46:03",
        "url": "https://files.pythonhosted.org/packages/30/c0/c79cc3fa85c9fee7c0df5fb7652308dd9bce2604177adb813cc8c50645b4/zope.exceptions-3.7.1.tar.gz"
      }
    ],
    "4.0.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "608c4089f225fc92fb0c8a5ff44ae337",
          "sha256": "a9785fddaf61c8018a9f4a0763db0aeb2eaac827f62de7e44e46da3cd6a6fd4d"
        },
        "downloads": 2622,
        "filename": "zope.exceptions-4.0.0.tar.gz",
        "has_sig": false,
        "md5_digest": "608c4089f225fc92fb0c8a5ff44ae337",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 21448,
        "upload_time": "2012-05-16T19:02:39",
        "url": "https://files.pythonhosted.org/packages/0d/18/28dd2b9957bdf53bb417fa1998fa543aa160acb1a60a0f5a2b11d95bff61/zope.exceptions-4.0.0.tar.gz"
      }
    ],
    "4.0.0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "347f09fd71bfccf57d150c926a3583d2",
          "sha256": "6d86069fe18ef9671c2e68673f5a3ad2c46cd85d703f3abba3cb2e8d544beaa6"
        },
        "downloads": 15087,
        "filename": "zope.exceptions-4.0.0.1.tar.gz",
        "has_sig": false,
        "md5_digest": "347f09fd71bfccf57d150c926a3583d2",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 21557,
        "upload_time": "2012-05-16T20:09:18",
        "url": "https://files.pythonhosted.org/packages/e3/46/72ad54d3b33657535383ab94792299463da0ee3a8770a16ea2902026118c/zope.exceptions-4.0.0.1.tar.gz"
      }
    ],
    "4.0.1": [
      {
        "comment_text": "",
        "digests": {
          "md5": "1f1ef3e8d740d19f4ae9df6df2ac5017",
          "sha256": "dd59bc8efd03b59d53be35b621d1b61742c24a553af7c5aa3edc127cef38a9b2"
        },
        "downloads": 34781,
        "filename": "zope.exceptions-4.0.1.zip",
        "has_sig": false,
        "md5_digest": "1f1ef3e8d740d19f4ae9df6df2ac5017",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 35591,
        "upload_time": "2012-08-20T15:20:30",
        "url": "https://files.pythonhosted.org/packages/78/4f/cae9f706b7713e7f8bf32eff23c64e58f5a6e38af3cd3888d2d612bc8ebf/zope.exceptions-4.0.1.zip"
      }
    ],
    "4.0.2": [
      {
        "comment_text": "",
        "digests": {
          "md5": "993e3826b5fc61f6b1c4cc691a12bf59",
          "sha256": "9c08fb287d77446221182e9b05d065a82a9998e5a4e254d311de783846f0be26"
        },
        "downloads": 3475,
        "filename": "zope.exceptions-4.0.2.tar.gz",
        "has_sig": false,
        "md5_digest": "993e3826b5fc61f6b1c4cc691a12bf59",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 23405,
        "upload_time": "2012-11-21T18:23:41",
        "url": "https://files.pythonhosted.org/packages/4a/40/7622734d1252e174cbf4f23c674d855a049bb7f4a42ff080a87aa828375c/zope.exceptions-4.0.2.tar.gz"
      }
    ],
    "4.0.3": [
      {
        "comment_text": "",
        "digests": {
          "md5": "893532486e1648d43798fc5ebd5ce5a1",
          "sha256": "f45a331594b940366c3a9ea0e3095c4a2959088b5a0f3107fcaaece67bf6242e"
        },
        "downloads": 2654,
        "filename": "zope.exceptions-4.0.3.zip",
        "has_sig": false,
        "md5_digest": "893532486e1648d43798fc5ebd5ce5a1",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 25084,
        "upload_time": "2012-12-10T17:09:06",
        "url": "https://files.pythonhosted.org/packages/18/63/2cbd4881279f145b6a36c60ff1d10c653307cd694ce57722ce422903c4ef/zope.exceptions-4.0.3.zip"
      }
    ],
    "4.0.4": [
      {
        "comment_text": "",
        "digests": {
          "md5": "70f8e22b34b7d4a3bdacbe46459131c2",
          "sha256": "549d2a1cda71297004c9f77343e4b0c37f6ca565ed8ee2d2cf9daa92165f518a"
        },
        "downloads": 3056,
        "filename": "zope.exceptions-4.0.4.zip",
        "has_sig": false,
        "md5_digest": "70f8e22b34b7d4a3bdacbe46459131c2",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 36460,
        "upload_time": "2012-12-13T09:51:29",
        "url": "https://files.pythonhosted.org/packages/6a/29/0f95d3943d4994e53e9def04577b56015dece8e6c83324c5a23150a59816/zope.exceptions-4.0.4.zip"
      }
    ],
    "4.0.5": [
      {
        "comment_text": "",
        "digests": {
          "md5": "c95569fcb444ae541777de7ae5297492",
          "sha256": "519659de1b407b1dff255fd3985a1cd7685a827ac6314a78fa28ad3f2439171b"
        },
        "downloads": 6375,
        "filename": "zope.exceptions-4.0.5.tar.gz",
        "has_sig": false,
        "md5_digest": "c95569fcb444ae541777de7ae5297492",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 24095,
        "upload_time": "2012-12-31T18:37:07",
        "url": "https://files.pythonhosted.org/packages/90/39/f8de8f1f8449f0943506ef74908988da4d43349db5f41984de5e662b0046/zope.exceptions-4.0.5.tar.gz"
      }
    ],
    "4.0.6": [
      {
        "comment_text": "",
        "digests": {
          "md5": "63cf38f8081e9e3b73eaf8725ba8dda6",
          "sha256": "35afae142d298b39efd84ad4c30c7676abcd78c2b1213c6006804b13d48db044"
        },
        "downloads": 54620,
        "filename": "zope.exceptions-4.0.6.zip",
        "has_sig": false,
        "md5_digest": "63cf38f8081e9e3b73eaf8725ba8dda6",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 34200,
        "upload_time": "2013-02-28T19:47:36",
        "url": "https://files.pythonhosted.org/packages/87/dd/4fbfaeac1a26a41b152016ba001ef226539aa9376897248b0b4129b4d183/zope.exceptions-4.0.6.zip"
      }
    ],
    "4.0.7": [
      {
        "comment_text": "",
        "digests": {
          "md5": "93daa7463373d755441d2b034709acac",
          "sha256": "98235d1a119ec0134076c20a827393c739532560a08f5670553ebf9a735238b8"
        },
        "downloads": 66329,
        "filename": "zope.exceptions-4.0.7.tar.gz",
        "has_sig": false,
        "md5_digest": "93daa7463373d755441d2b034709acac",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 413151,
        "upload_time": "2014-03-19T18:39:04",
        "url": "https://files.pythonhosted.org/packages/5a/da/c44a29d6e8690709fb34a6f38e40ee03e766c27f81a7da4b16a18ed5a09b/zope.exceptions-4.0.7.tar.gz"
      }
    ],
    "4.0.8": [
      {
        "comment_text": "",
        "digests": {
          "md5": "c6f9b3905a48ba0487f82d95fba71c0c",
          "sha256": "f43bcbb7e4f043565d4322db6ea50dd5a7b71cd03bb37f66791d6b6394529d7f"
        },
        "downloads": 28879,
        "filename": "zope.exceptions-4.0.8.tar.gz",
        "has_sig": false,
        "md5_digest": "c6f9b3905a48ba0487f82d95fba71c0c",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 26126,
        "upload_time": "2015-08-13T18:54:22",
        "url": "https://files.pythonhosted.org/packages/8f/b7/eba9eca6841fa47d9a30f71a602be7615bff4f8e11f85c2840b88a77c68a/zope.exceptions-4.0.8.tar.gz"
      }
    ],
    "4.1.0": [
      {
        "comment_text": "",
        "digests": {
          "md5": "f216f4b90ec12ba506e83de65e80bd35",
          "sha256": "8925ef5ed8c1c3b628a71d5f37e87de7f42c7151a1619152c9711618bd39a984"
        },
        "downloads": 0,
        "filename": "zope.exceptions-4.1.0-py2.py3-none-any.whl",
        "has_sig": true,
        "md5_digest": "f216f4b90ec12ba506e83de65e80bd35",
        "packagetype": "bdist_wheel",
        "python_version": "py2.py3",
        "size": 20065,
        "upload_time": "2017-06-13T20:41:32",
        "url": "https://files.pythonhosted.org/packages/c1/b1/642f33446b521108d565204e3f509812f6f1cdedb7e0f89e1d4a8e63aa4b/zope.exceptions-4.1.0-py2.py3-none-any.whl"
      },
      {
        "comment_text": "",
        "digests": {
          "md5": "e08aa501e6b019d16b078b2b2d7de497",
          "sha256": "f1c086abddc9f2050df5824ff7ab8ece3285c8e28453a29ee761effbc5e592ad"
        },
        "downloads": 0,
        "filename": "zope.exceptions-4.1.0.tar.gz",
        "has_sig": false,
        "md5_digest": "e08aa501e6b019d16b078b2b2d7de497",
        "packagetype": "sdist",
        "python_version": "source",
        "size": 26605,
        "upload_time": "2017-04-12T07:57:47",
        "url": "https://files.pythonhosted.org/packages/ff/90/f99db8618a8fe44691af5c82baf55a71d7e94744e7736f2c09807747bf45/zope.exceptions-4.1.0.tar.gz"
      }
    ]
  },
  "urls": [
    {
      "comment_text": "",
      "digests": {
        "md5": "f216f4b90ec12ba506e83de65e80bd35",
        "sha256": "8925ef5ed8c1c3b628a71d5f37e87de7f42c7151a1619152c9711618bd39a984"
      },
      "downloads": 0,
      "filename": "zope.exceptions-4.1.0-py2.py3-none-any.whl",
      "has_sig": true,
      "md5_digest": "f216f4b90ec12ba506e83de65e80bd35",
      "packagetype": "bdist_wheel",
      "python_version": "py2.py3",
      "size": 20065,
      "upload_time": "2017-06-13T20:41:32",
      "url": "https://files.pythonhosted.org/packages/c1/b1/642f33446b521108d565204e3f509812f6f1cdedb7e0f89e1d4a8e63aa4b/zope.exceptions-4.1.0-py2.py3-none-any.whl"
    },
    {
      "comment_text": "",
      "digests": {
        "md5": "e08aa501e6b019d16b078b2b2d7de497",
        "sha256": "f1c086abddc9f2050df5824ff7ab8ece3285c8e28453a29ee761effbc5e592ad"
      },
      "downloads": 0,
      "filename": "zope.exceptions-4.1.0.tar.gz",
      "has_sig": false,
      "md5_digest": "e08aa501e6b019d16b078b2b2d7de497",
      "packagetype": "sdist",
      "python_version": "source",
      "size": 26605,
      "upload_time": "2017-04-12T07:57:47",
      "url": "https://files.pythonhosted.org/packages/ff/90/f99db8618a8fe44691af5c82baf55a71d7e94744e7736f2c09807747bf45/zope.exceptions-4.1.0.tar.gz"
    }
  ]
}